schemastore: fix rename tables when tidb version <= v8.1.x (#4388)
close pingcap/ticdc#4392

diff --git a/tests/integration_tests/_utils/test_prepare b/tests/integration_tests/_utils/test_prepare
--- a/tests/integration_tests/_utils/test_prepare
+++ b/tests/integration_tests/_utils/test_prepare
@@ -93,3 +93,76 @@ else
 fi
 
 export TEST_OUT_DATA_DIR=test_out_data
+
+function get_tidb_release_version() {
+	local tidbHost=${1:-$UP_TIDB_HOST}
+	local tidbPort=${2:-$UP_TIDB_PORT}
+
+	mysql -uroot -h${tidbHost} -P${tidbPort} --default-character-set utf8mb4 -e "select tidb_version()\G" \
+		| sed -nE 's/.*Release Version:[[:space:]]*(v[0-9]+(\.[0-9]+){0,2}([-.+][0-9A-Za-z.-]+)?).*/\1/p' \
+		| head -n1
+}
+
+function normalize_tidb_semver_triplet() {
+	local rawVersion=${1#v}
+	rawVersion=${rawVersion%%-*}
+	rawVersion=${rawVersion%%+*}
+
+	local major minor patch
+	IFS='.' read -r major minor patch <<<"$rawVersion"
+	major=${major:-0}
+	minor=${minor:-0}
+	patch=${patch:-0}
+
+	if ! [[ "$major" =~ ^[0-9]+$ && "$minor" =~ ^[0-9]+$ && "$patch" =~ ^[0-9]+$ ]]; then
+		return 1
+	fi
+
+	echo "$major $minor $patch"
+}
+
+function tidb_version_less_than() {
+	local currentVersion=$1
+	local minVersion=$2
+
+	local currentTriplet minTriplet
+	currentTriplet=$(normalize_tidb_semver_triplet "$currentVersion") || return 1
+	minTriplet=$(normalize_tidb_semver_triplet "$minVersion") || return 1
+
+	local -a currentParts minParts
+	read -r -a currentParts <<<"$currentTriplet"
+	read -r -a minParts <<<"$minTriplet"
+
+	local idx currentPart minPart
+	for idx in 0 1 2; do
+		currentPart=$((10#${currentParts[$idx]}))
+		minPart=$((10#${minParts[$idx]}))
+		if ((currentPart < minPart)); then
+			return 0
+		fi
+		if ((currentPart > minPart)); then
+			return 1
+		fi
+	done
+
+	return 1
+}
+
+function skip_if_tidb_version_less_than() {
+	local minVersion=$1
+	local tidbHost=${2:-$UP_TIDB_HOST}
+	local tidbPort=${3:-$UP_TIDB_PORT}
+	local testName=${TEST_NAME:-unknown}
+
+	local tidbReleaseVersion
+	tidbReleaseVersion=$(get_tidb_release_version "$tidbHost" "$tidbPort" || true)
+	if [ -z "$tidbReleaseVersion" ]; then
+		echo "[$(date)] failed to parse TiDB release version from ${tidbHost}:${tidbPort}, continue test case ${testName}"
+		return
+	fi
+
+	if tidb_version_less_than "$tidbReleaseVersion" "$minVersion"; then
+		echo "[$(date)] <<<<<< skip test case ${testName}, TiDB version ${tidbReleaseVersion} is less than ${minVersion} >>>>>>"
+		exit 0
+	fi
+}
